name: practica_github_actions
on:
  push:
    branches:
      - main
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Execute Linter
        run: npm install && npm run lint
  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
      