name: practica_github_actions
on:
  push:
    branches:
      - main
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Execute Linter
        run: npm install && npm run lint
  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypress_result
      - name: Create Cypress Artifact
        run: echo ${{ steps.cypress_result.outcome }} > result.txt
      - name: Upload Cypress Result
        uses: actions/upload-artifact@v3
        with:
          name: cypress_result_txt
          path: result.txt
  Add_badge_job:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: Cypress_job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Cypress Result
        uses: actions/download-artifact@v3
        with:
          name: cypress_result_txt
      - name: Get Cypress Result
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: cypress_status
      - name: Mod Readme
        uses: ./.github/actions/mod_readme
        with:
          resultado: ${{ steps.cypress_status.outputs.cypress_outcome }}
      - name: Push readme
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Joaquim Ribera Soriano"
          author_email: "joaquimdaweb@gmail.com"
          message: "Readme Updated"
          push: true
  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Aplication
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: joaquimrs
          vercel-project-id: practica-github-actions-01
          working-directory: ./