name: practica_github_actions
on:
  push:
    branches:
      - main
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Execute Linter
        run: npm install && npm run lint